version: '3'

services:
#  postgres:
#    image: postgres
#    container_name: postgres-container
#    environment:
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: mabsplace
#    ports:
#      - 5432:5432
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
#  #      - ./init-scripts/create-db.sql:/docker-entrypoint-initdb.d/init.sql

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: mabsplace
      MYSQL_USER: karlmabs
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  #  spring-app:
  #    build: .
  #    container_name: spring-app-container
  #    ports:
  #      - 8080:8080
  #    restart: on-failure
  #    depends_on:
  #      - postgres

  minio:
    image: quay.io/minio/minio:latest
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-client:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/mabsplace;
      while true; do sleep 10000; done"

volumes:
  minio-data: