spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mabsplace
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mabsplace:
  openapi:
    url: http://localhost:8080

app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect

minio:
  url: http://localhost:9000
  access-key: minio
  secret-key: minio123
  bucket-name: mabsplace
