spring:
  datasource:
    url: jdbc:mysql://mysql/mabsplace
    username: karlmabs
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 60000ms
  cache:
    type: redis
    redis:
      time-to-live: 300000
      cache-null-values: false

mabsplace:
  openapi:
    url: https://back.mabsplace.app

app:
  cors:
    allowedOrigins: https://mabsplace.app,https://www.mabsplace.app
  oauth2:
    authorizedRedirectUris:
      - https://mabsplace.app/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect

minio:
  url: http://minio:9000
  access-key: minio
  secret-key: minio123
  bucket-name: mabsplace
