spring:
  profiles:
    active: dev  # Default profile
  mail:
    host: smtp.gmail.com
    port: 587
    username: mabsplace2024@gmail.com
    password: hofq zhhw anvf bzro
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000ms

  cache:
    type: redis
    redis:
      time-to-live: 300000  # 5 minutes in milliseconds
      cache-null-values: false

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 497027706625-6l43ei9kjs5dc5hrskn94uqq2qcc5roo.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile
          facebook:
            clientId: 121189305185277
            clientSecret: 42ffe5aa7379e8326387e0fe16f34132
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            clientId: d3e47fc2ddd966fa4352
            clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

mabsplace:
  app:
    jwtCookieName: mabsplace
    jwtSecret: ======================mabsplace=Spring===========================
    jwtExpirationMs: 86400000
    baseUrl: https://my-coolpay.com/api/1ab431cc-4586-4521-9e02-a53b24f1ecdb/
    privateKey: QYVLTmSoDoOsAIi4NZkah6QZXi9PUJkXi0pMc6QeLyRd0rnokyB5p1XhZs8talt8
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://back.mabsplace.app
  google:
    clientId: 497027706625-6l43ei9kjs5dc5hrskn94uqq2qcc5roo.apps.googleusercontent.com
    clientSecret: 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

app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
    

discord:
  webhook:
    payment-reminders: https://discord.com/api/webhooks/1424714395564642364/2YgOrgi4ZXabfoYRqH_hZUgKl2I-21th_o56ug7-JKxKtgoSCRGK-oV2tgyH4Qf45rNm
    subscription-renewals: https://discord.com/api/webhooks/1426666147431973017/ljJdSkvdDO8LnyuARqBWxU1sWx1x4FJaMhSXcPoswjbT9dBx3ZpM97B92DQw9OOQqq8A
    profile-security-audit: https://discord.com/api/webhooks/1429947685737205901/ilGhUQ-kAQTH8DKPK9QQ8VQgSFb06w3g7pUOIqI5UF_2RuhAR0hF9srNh7dls7VbvXCZ

whatsapp:
  api:
    url: https://graph.facebook.com/v22.0
    token: EAAQxDeXZAlxsBPxzUlaV7ZBHxcGhj18OJZAPEesKuS0obs7MRHqb18ZAb8uL2QZCJScZCgIo4kckeJmdTiZBUVJGVamOmZCbYptZA5cpj3l2Qd57dQr9FJXI1lcHrotTZCZBrPuNkebwuxOTQxpVvZCHLIFT04avbxoWy1VVkil8k8CWeF4mcPnqPbwRhW9TGMLZCeMAHaGAe5YMnz3Jso0jP1EbZC1JqEhlWEIgcf3TujHLU4ZBVNinUNnsaWNmnldHYt8Ie8laZCZChdDN29k3NYe2vhic95QItioAruC3JNnxhlAZDZD
  phone:
    number:
      id: 675211405670204
  templates:
    subscription-renewed: subscription_renewed
    subscription-renewal-failed: subscription_renewal_failed
    subscription-expired: subscription_expired
    subscription-expiring-soon: subscription_expiring_soon

# OneSignal Configuration
onesignal:
  app:
    id: ${ONESIGNAL_APP_ID:079f270c-81e2-43f8-8a51-266c69b6fc8a}
  api:
    key: ${ONESIGNAL_API_KEY:os_v2_app_a6psodeb4jb7rcsrezwgtnx4riza22cafoiutsfjsfkdzstvkb32msqpicfo44atp3oer54udbtuoaatucqv5vgeqqaekgjwroqnv7a}
    url: https://onesignal.com/api/v1
  user:
    auth:
      key: ${ONESIGNAL_USER_AUTH_KEY:za22cafoiutsfjsfkdzstvkb3}
  email:
    from:
      default: ${ONESIGNAL_FROM_EMAIL:noreply@mabsplace.app}
  templates:
    email:
      verification-code: verification-code
      payment-reminder: payment-reminder
      subscription-renewed: subscription-renewed
      subscription-expiring: subscription-expiring
      subscription-expired: subscription-expired
      renewal-failed: renewal-failed

verification:
  code:
    expiration:
      minutes: 15
