spring:
  datasource:
    url: jdbc:mysql://mysql/mabsplace
    username: karlmabs
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

mabsplace:
  openapi:
    url: https://back.mabsplace.com

app:
  cors:
    allowedOrigins: https://mabsplace.com,https://www.mabsplace.com
  oauth2:
    authorizedRedirectUris:
      - https://mabsplace.com/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect

minio:
  url: http://minio:9000
  access-key: minio
  secret-key: minio123
  bucket-name: mabsplace
