apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      nodeSelector:
        "kubernetes.io/hostname": ubuntu
      containers:
        - name: spring-app
          image: karlmabs/spring-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env: # Setting Environmental Variables
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: DB_HOST   # Setting Database host address
              value: mysql
            - name: DB_NAME  # Setting Database name
              value: mabsplace
            - name: DB_USERNAME  # Setting Database username
              value: karlmabs
            - name: DB_PASSWORD # Setting Database password
              value: password
          volumeMounts:
            - name: spring-logs
              mountPath: /app/logs
      volumes:
        - name: spring-logs
          persistentVolumeClaim:
            claimName: spring-logs-pvc