apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: karlmabs/spring-app:latest
          ports:
            - containerPort: 8080
          env: # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address
              value: mysql
            - name: DB_NAME  # Setting Database name
              value: mabsplace
            - name: DB_USERNAME  # Setting Database username
              value: karlmabs
            - name: DB_PASSWORD # Setting Database password
              value: password
#          volumeMounts:
#            - name: config-volume
#              mountPath: /config
#      volumes:
#        - name: config-volume
#          configMap:
#            name: spring-config