name: Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Docker Image
        run: |
          docker build -t karlmabs/spring-app:latest .
          docker tag karlmabs/spring-app:latest karlmabs/spring-app:${{ github.sha }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push karlmabs/spring-app:latest
          docker push karlmabs/spring-app:${{ github.sha }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Authenticate with Kubernetes
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Apply ConfigMap
        run: |
          kubectl --kubeconfig=k8s/kubeconfig apply -f k8s/spring-config.yaml

      - name: Create or Update Deployment
        run: |
          kubectl --kubeconfig=k8s/kubeconfig set image deployment/spring-app spring-app=karlmabs/spring-app:${{ github.sha }}
          kubectl --kubeconfig=k8s/kubeconfig apply -f k8s/deployment.yaml
          kubectl --kubeconfig=k8s/kubeconfig apply -f k8s/service.yaml

      - name: Verify Deployment
        run: |
          kubectl --kubeconfig=k8s/kubeconfig rollout status deployment spring-app
          kubectl --kubeconfig=k8s/kubeconfig get pods